name: Code Validation
run-name: ${{github.actor}} is running the github actions

## Basically pipeline will run on two types of events

on: 
  push:
    paths:
      - 'force-app/**'
    branches:
      - feature/*
      - bugfix/*
      - hotfix/*
      
jobs:
  build-and-deploy:
    runs-on: ubuntu

    steps:
      - run: echo "This is my first-job"
        name: "This is my first job message"
      - name: checkout code
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Install SFDX CLI
        run: npm install sfdx-cli --global
        
      - name: display user
        run: sfdx org display user
