name: PRODUCTION PIPELINE
run-name: ${{github_actor}} is running the github actions

## Basically pipeline will run on two types of events

on: [push, pull_request]

jobs:
  build-and-deploy: # Name of the JOB
    runs-on: ubuntu-latest # github hosted

    steps:
      - run: echo "This is my first-job"
        name: "This is my first job message"

  clean-up:
    runs-on: ubuntu-latest

    steps:
      - run: echo "This is my second job"
        name: echo "This is my second job message"

